spring:
    yarn:
        appName: xd-admin
        applicationDir: /xd/app/
        fsUri: hdfs://localhost:8020
        rmAddress: localhost:8032
        schedulerAddress: localhost:8030
        appmaster:
            appmasterClass: org.springframework.yarn.am.StaticEventingAppmaster
            memory: 768M
            containerCount: 1
            containerRunner: org.springframework.xd.dirt.server.AdminServerApplication
            arguments: {-Dxd.home: "file:./spring-xd-yarn.zip", -DPORT: 9393, -Dspring.application.name: "admin", -Dlogging.config: "file:./spring-xd-yarn.zip/config/xd-admin-logger.properties"}
            waitLatch: false
            classpath:
              - "./spring-xd-yarn.zip"
              - "./spring-xd-yarn.zip/conf"
              - "./spring-xd-yarn.zip/lib/*"
