spring:
    yarn:
        appName: xd-container
        applicationDir: /xd/app/
        fsUri: hdfs://localhost:8020
        rmAddress: localhost:8032
        schedulerAddress: localhost:8030
        appmaster:
            appmasterClass: org.springframework.yarn.am.StaticEventingAppmaster
            memory: 512M
            containerCount: 1
            containerRunner: org.springframework.xd.dirt.server.LauncherApplication
            arguments: {-DxdHomeDir: "./spring-xd-yarn.zip", -Dspring.application.name: "container"}
            waitLatch: false
            classpath:
              - "./spring-xd-yarn.zip"
              - "./spring-xd-yarn.zip/config"
              - "./spring-xd-yarn.zip/lib/*"
              - "./spring-xd-yarn.zip/modules/processor/scripts"
