spring:
    yarn:
        appName: xd-container
        applicationDir: /xd/app/
        fsUri: hdfs://localhost:8020
        rmAddress: localhost:8032
        schedulerAddress: localhost:8030
        client:
            memory: 512M
            files:
              - "file:app/spring-xd-yarn.zip"
              - "file:build/libs/xd-yarn-appmaster-0.1.0.SNAPSHOT.jar"
            appmasterFile: xd-yarn-appmaster-0.1.0.SNAPSHOT.jar
            arguments: {--spring.config.name: container, --spring.yarn.appmaster.containerCount: "${containers:1}"}
